// imports and directives
import type { Metadata } from "next";
import React from "react";

// global styles
import "@/shared/app/reset.css";
import "@/shared/app/adaptive.scss";
import "@/shared/app/palette.css";
import "@/shared/app/fonts.css";
import "@/shared/app/typo.css";
import "@/shared/app/icon.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
