// imports and directives
import type { Metadata } from "next";

// global styles
// import "@/shared/app/reset.pcss";
// import "@/shared/app/palette.pcss";
// import "@/shared/app/typo.pcss";
// import "@/shared/app/icon.pcss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
